# These are supported funding model platforms

github: [makaulucky]
patreon: luckymakau
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: nyumbani_Catholic_Disp
otechie: # Replace with a single Otechie username
custom: ["https://www.paypal.com/luckymakau",] 
